export enum ProductCategory {
  NECKLACE = 'NECKLACE',
  BRACELET = 'BRACELET',
  EARRING = 'EARRING',
  RING = 'RING',
  BODY_JEWELLERY = 'BODY_JEWELLERY',
  PHONE_CHARM = 'PHONE_CHARM',
  COMBO_AND_HAMPERS = 'COMBO_AND_HAMPERS',
  MEN_COLLECTION = 'MEN_COLLECTION',
  OTHERS = 'OTHERS',
}
