export enum ProductCategory {
  NECKLACE = 'NECKLACE',
  BRACELET = 'BRACELET',
  EARRING = 'EARRING',
  ANKLET = 'ANKLET',
  BODY_JEWELLERY = 'BODY_JEWELLERY',
  PHONE_STRAP = 'PHONE_STRAP',
  RING = 'RING',
  CHARM = 'CHARM',
  OTHERS = 'OTHERS',
}
